<?php

return [
    'admin' => [
        'AdminController@index',
        'AdminController@ajax',
        'AdminController@notify',
        'CategoriesController@index',
        'CategoriesController@create',
        'CategoriesController@edit',
        'CategoriesController@destroy',
        'CategoriesController@update',
        'CategoriesController@store',

        'ModulesController@index',
        'ModulesController@create',
        'ModulesController@edit',
        'ModulesController@destroy',
        'ModulesController@update',
        'ModulesController@store',


        'PostsController@index',
        'PostsController@create',
        'PostsController@edit',
        'PostsController@destroy',
        'PostsController@update',
        'PostsController@store',

        'TagsController@index',
        'TagsController@create',
        'TagsController@edit',
        'TagsController@destroy',
        'TagsController@update',
        'TagsController@store',

        'BannersController@index',
        'BannersController@create',
        'BannersController@edit',
        'BannersController@destroy',
        'BannersController@update',
        'BannersController@store',

        'PositionsController@index',
        'PositionsController@create',
        'PositionsController@edit',
        'PositionsController@destroy',
        'PositionsController@update',
        'PositionsController@store',

        'MedicinesController@index',
        'MedicinesController@create',
        'MedicinesController@edit',
        'MedicinesController@destroy',
        'MedicinesController@update',
        'MedicinesController@store',

        'DiseasesController@index',
        'DiseasesController@create',
        'DiseasesController@edit',
        'DiseasesController@destroy',
        'DiseasesController@update',
        'DiseasesController@store',

        'ProductsController@index',
        'ProductsController@create',
        'ProductsController@edit',
        'ProductsController@destroy',
        'ProductsController@update',
        'ProductsController@store',

        'VideosController@index',
        'VideosController@create',
        'VideosController@edit',
        'VideosController@destroy',
        'VideosController@update',
        'VideosController@store',

        'CouponsController@index',
        'CouponsController@create',
        'CouponsController@edit',
        'CouponsController@destroy',
        'CouponsController@update',
        'CouponsController@store',

        'CodesController@index',
        'CodesController@create',
        'CodesController@edit',
        'CodesController@destroy',
        'CodesController@update',
        'CodesController@store',

        'ContactsController@index',
        'ContactsController@create',
        'ContactsController@edit',
        'ContactsController@destroy',
        'ContactsController@update',
        'ContactsController@store',

        'OrdersController@index',
        'OrdersController@create',
        'OrdersController@edit',
        'OrdersController@destroy',
        'OrdersController@update',
        'OrdersController@store',

        'DeliveriesController@index',
        'DeliveriesController@create',
        'DeliveriesController@edit',
        'DeliveriesController@destroy',
        'DeliveriesController@update',
        'DeliveriesController@store',


    ],

    'editor' => [
        'AdminController@index',
        'AdminController@ajax',
        'AdminController@notify',
        'CategoriesController@index',
        'CategoriesController@create',
        'CategoriesController@edit',
        'CategoriesController@destroy',
        'CategoriesController@update',
        'CategoriesController@store',

        'ModulesController@index',
        'ModulesController@create',
        'ModulesController@edit',
        'ModulesController@destroy',
        'ModulesController@update',
        'ModulesController@store',

        'PostsController@index',
        'PostsController@create',
        'PostsController@edit',
        'PostsController@destroy',
        'PostsController@update',
        'PostsController@store',



        'TagsController@index',
        'TagsController@create',
        'TagsController@edit',
        'TagsController@destroy',
        'TagsController@update',
        'TagsController@store',

        'BannersController@index',
        'BannersController@create',
        'BannersController@edit',
        'BannersController@destroy',
        'BannersController@update',
        'BannersController@store',

        'PositionsController@index',
        'PositionsController@create',
        'PositionsController@edit',
        'PositionsController@destroy',
        'PositionsController@update',
        'PositionsController@store',

        'MedicinesController@index',
        'MedicinesController@create',
        'MedicinesController@edit',
        'MedicinesController@destroy',
        'MedicinesController@update',
        'MedicinesController@store',

        'DiseasesController@index',
        'DiseasesController@create',
        'DiseasesController@edit',
        'DiseasesController@destroy',
        'DiseasesController@update',
        'DiseasesController@store',

        'ProductsController@index',
        'ProductsController@create',
        'ProductsController@edit',
        'ProductsController@destroy',
        'ProductsController@update',
        'ProductsController@store',


        'VideosController@index',
        'VideosController@create',
        'VideosController@edit',
        'VideosController@destroy',
        'VideosController@update',
        'VideosController@store',

        'CouponsController@index',
        'CouponsController@create',
        'CouponsController@edit',
        'CouponsController@destroy',
        'CouponsController@update',
        'CouponsController@store',

        'CodesController@index',
        'CodesController@create',
        'CodesController@edit',
        'CodesController@destroy',
        'CodesController@update',
        'CodesController@store',

        'ContactsController@index',
        'ContactsController@create',
        'ContactsController@edit',
        'ContactsController@destroy',
        'ContactsController@update',
        'ContactsController@store',

        'OrdersController@index',
        'OrdersController@create',
        'OrdersController@edit',
        'OrdersController@destroy',
        'OrdersController@update',
        'OrdersController@store',

        'DeliveriesController@index',
        'DeliveriesController@create',
        'DeliveriesController@edit',
        'DeliveriesController@destroy',
        'DeliveriesController@update',
        'DeliveriesController@store',

    ],

    'posts' => [
        'AdminController@index',

        'PostsController@index',
        'PostsController@create',
        'PostsController@edit',
        'PostsController@destroy',
        'PostsController@update',
        'PostsController@store',
    ],

];